### ISSUE TITLE
You promised to release the code by the end of this year 

### ISSUE THREAD

**Issue by jenshadlich** [phreakAI/MetasploitGym#1]
😊

**Comment by jenshadlich** [comment]
@SJCaldwell I don't want to bother you too much but the year is over ;-)

**Comment by SJCaldwell** [comment]
Very true! Sorry I'm late, some things at work have slowed me down a bit. I'll release the code here shortly. 

Thanks for your patience! Looking forward to everyone getting to take a crack at it.

**Comment by SJCaldwell** [comment]
Alright, this weekend for sure. I've received a couple of very kind notes/comments and while the code won't be in the most ideal state, I would rather have all of you get to take a crack at it. Thanks very much for your patience, and expect it this Sunday evening!

**Comment by SJCaldwell** [comment]
Thanks for your patience. We've got our 0.1.0 alpha out!
